apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  application.yml: |
    spring:
      kafka:
        bootstrap-servers: {{ .Values.global.kafka.bootstrapServers }}
    app:
      kafka:
        customer-topic: {{ .Values.global.kafka.customerTopic }}
        webhook-topic: webhook-consumer
      api:
        version: v1
        retry:
          max-attempts: 3
          max-delay: 2000
