apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-order-api
  labels:
    app: order-api
spec:
  type: {{ .Values.orderApi.service.type }}
  ports:
    - port: {{ .Values.orderApi.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: order-api
