#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: {{ .Release.Name }}-order-status-api
#  labels:
#    app: order-status-api
#spec:
#  replicas: {{ .Values.orderStatusApi.replicaCount }}
#  selector:
#    matchLabels:
#      app: order-status-api
#  template:
#    metadata:
#      labels:
#        app: order-status-api
#    spec:
#      containers:
#        - name: order-status-api
#          image: "{{ .Values.orderStatusApi.image.repository }}:{{ .Values.orderStatusApi.image.tag }}"
#          imagePullPolicy: {{ .Values.orderStatusApi.image.pullPolicy }}
#          ports:
#            - containerPort: 8080
#          resources:
#            {{- toYaml .Values.orderStatusApi.resources | nindent 12 }}
