apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-order-api
  labels:
    app: order-api
spec:
  replicas: {{ .Values.orderApi.replicaCount }}
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
        - name: order-api
          image: "{{ .Values.orderApi.image.repository }}:{{ .Values.orderApi.image.tag }}"
          imagePullPolicy: {{ .Values.orderApi.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.global.kafka.bootstrapServers }}
            - name: APP_KAFKA_CUSTOMER_TOPIC
              value: {{ .Values.global.kafka.customerTopic }}
          resources:
            {{- toYaml .Values.orderApi.resources | nindent 12 }}
